### ISSUE TITLE
When I do add a contact, the app responds with required field error but in the profile the fields are not required

### ISSUE THREAD

**Issue by muniodiego** [agileware/au.com.agileware.civicontact#2] opened 2020-04-01 13:35 UTC
**Mobile Device:**
 - Device Hardware: Samsung Galaxy J7 Prime
 - OS & Version: Android 8.1

**CiviCRM / Website Environment:**
 - Server OS: Debian 9
 - PHP Version: PHP 7.2.18
- CiviCRM Version: 5.21.2
- Website CMS: Drupal 7.69

**Describe the bug**
When I do add a contact, the app responds with required field error but in the profile the fields are not required

**To Reproduce**
Steps to reproduce the behaviour:
1. New contact.
2. Enter name, surname and e-mail
3. Clic save contact.
4. Required field error.

**Expected behaviour**
None of the profile fields are required, therefore you should not report such an error.

**Screenshots**
![Screenshot_20200401-091936_CiviContact](https://user-images.githubusercontent.com/56721994/78143315-7af83700-7404-11ea-81dc-adb34e15ffbb.jpg)

**Comment by agileware-justin** [comment] 2020-04-03 02:59
@muniodiego thanks for the report, we will investigate.

**Comment by agileware-justin** [comment] 2021-02-19 00:53
Was unable to reproduce this bug, closing.

**Closed by agileware-justin** 2021-02-19 00:53 UTC
Labels: bug
