### ISSUE TITLE
images are broken

### ISSUE THREAD

**Issue by larp-welt** [agileware/au.com.agileware.civicontact#1] opened 2020-03-25 19:42 UTC
I have installed CiviContact (great app) an Android on two devices. One is an Samsung Galaxy S8 and the other is an Samsung Tab A. 

On both login worked on the first try using the QRCode, syncing of 110 contacts took a while but worked fine. 

But all contact images are broken. 

![Screenshot_20200325-203058_CiviContact](https://user-images.githubusercontent.com/392672/77578314-a21ca900-6ed8-11ea-8366-35c907c02286.jpg)

![Screenshot_20200325-203945_CiviContact](https://user-images.githubusercontent.com/392672/77578573-0f303e80-6ed9-11ea-9771-a0eb077959ce.jpg)

I can't see any errors in the apaches error and access log.

I'm using CiviCRM 5.20.1 under Ubuntu 18.04.

**Comment by agileware-justin** [comment] 2020-03-25 20:35
@larp-welt thanks for the report and screenshots.

I would suggest confirming that the CiviContact app is attempting to fetch the images first. This should be recorded as GET requests in the Apache access log for the CiviCRM Image Upload URL as defined in the CiviCRM Settings - Resource URLs.

So disconnect CiviContact app from your CiviCRM site and re-connect, watch the Apache access log.

If that doesn't provide any insights. Then the next step is to provide a few more details, see below.

- Did you read the [CiviContact API README](https://github.com/agileware/au.com.agileware.civicontactapi/blob/master/README.md)? Yes / No
- Is the CiviCRM site accessible on the public Internet and is not password-protected (Intranet or private website)? Yes / No
- Is CiviCRM SSL enabled? Yes / No
- Has the CiviCRM Base URL been set on the CiviCRM site? Yes / No
- Have the CiviCRM Resource URLs been set correctly? Yes / No
- Have the CiviCRM Upload Directories been set correctly? Yes / No
- Has the latest version of CiviContact API extension been installed? Yes / No
- Has this been tested using the latest version of CiviContact app? Yes / No
- Has this been tested on a production CiviCRM site? Yes / No

**If you answered "No" to any of the above, then please fix the item first and re-test.**

**Mobile Device (please complete the following information):**
 - Device Hardware: [e.g. iPhone6]
 - OS & Version: [e.g. iOS8.1]

**CiviCRM / Website Environment (please complete the following information):**
 - Server OS: [e.g. CentOS, Ubuntu]
 - PHP Version: [e.g. PHP 7.1, PHP 7.2, PHP 7.3]
- CiviCRM Version: [e.g. 5.23.3]
- Website CMS: [e.g. WordPress, Drupal 6 / 7 / 8 /9, Joomla, if other specify ]

**Comment by agileware-justin** [comment] 2020-03-31 21:24
@larp-welt how did you go, has this been resolved?

**Comment by agileware-justin** [comment] 2021-02-19 00:48
Unable to reproduce, closing.

**Closed by agileware-justin** 2021-02-19 00:48 UTC
